// <auto-generated />
namespace NguyenBinhMinh_04.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtableTinhThanh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtableTinhThanh));
        
        string IMigrationMetadata.Id
        {
            get { return "202106060822157_add-table-TinhThanh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
