// <auto-generated />
namespace NguyenBinhMinh_04.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class table_Demo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_Demo));
        
        string IMigrationMetadata.Id
        {
            get { return "202106100216120_table_Demo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
